export { default as ChevronDownIcon } from '@/public/assets/svg/chevron-down.svg'
export { default as ChevronUpIcon } from '@/public/assets/svg/chevron-up.svg'
export { default as CloseXIcon } from '@/public/assets/svg/close-x.svg'
export { default as EyeCloseIcon } from '@/public/assets/svg/eye-close.svg'
export { default as EyeOpenIcon } from '@/public/assets/svg/eye-open.svg'
export { default as MenuFriesIcon } from '@/public/assets/svg/menu-fries.svg'
export { default as PlayIcon } from '@/public/assets/svg/play-icon.svg'
export { default as ArrowRightMiniIcon } from '@/public/assets/svg/arrow-right-mini.svg'
