import type { Metadata, Viewport } from 'next'
import '@/styles/globals.css'
import '@/styles/bg.css'
import '@/styles/tailwind.css'
import '@/styles/animation.css'
import MetaTags from '@/Meta'
import LandingPageNavbar from '@/layouts/landing-page-navbar'
import LandingPageFooter from '@/layouts/landing-page-footer'

export const metadata: Metadata = {
  title: 'Home Page - InnerCity Mission HQ',
  description:
    'The InnerCity Mission for Children is a full-fledged faith-based Non-Governmental Organisation [NGO] in Consultative Status with the United Nations [UN]; It is under the auspices of Pastor Chris Oyakhilome Foundation.',
  icons: {
    icon: '/next.svg',
    shortcut: '/next.svg',
    apple: '/next.svg',
  },
  manifest: '/manifest.json',
  keywords: [
    'the innercity mission for children',
    'the innercity mission children',
    'the innercity children',
    'the innercity mission',
    'the innercity',
    'inner city',
    'innercity',
    'Christ Embassy',
    'Believers Loveworld',
    'BLW',
    'Inner',
    'City',
  ],
  authors: [
    {
      name: 'The InnerCity Mission For Children',
      url: 'https://theinnercitymission.ngo',
    },
  ],
  publisher: 'The InnerCity Mission For Children',
  robots: {
    index: true,
    follow: true,
    'max-image-preview': 'large',
    'max-video-preview': -1,
    'max-snippet': -1,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
    },
  },
  appleWebApp: {
    title: 'Home Page - InnerCity Mission HQ',
    statusBarStyle: 'black-translucent',
  },
  // verification: {
  //   google: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  // },
  // openGraph: {
  //   title: 'Home Page - InnerCity Mission HQ',
  //   description:
  //     'The InnerCity Mission for Children is a full-fledged faith-based Non-Governmental Organisation [NGO] in Consultative Status with the United Nations [UN]; It is under the auspices of Pastor Chris Oyakhilome Foundation.',
  //   type: 'website',
  //   locale: 'en_US',
  //   url: 'https://theinnercitymission.ngo',
  //   siteName: 'The InnerCity Mission For Children',
  //   images: [
  //     {
  //       url: '/image.png',
  //       width: 1200,
  //       height: 630,
  //       alt: 'The InnerCity Mission For Children',
  //     },
  //   ],
  // },
  // twitter: {
  //   card: 'summary_large_image',
  //   title: 'Home Page - InnerCity Mission HQ',
  //   description: 'Generated by create next app',
  //   creator: '@innercityhq',
  // },
}

export const viewport: Viewport = {
  themeColor: '#0080DE',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <MetaTags title="Home Page - InnerCity Mission HQ" />
      </head>
      <body className="">
        <div>
          <LandingPageNavbar/>
          {children}
          <LandingPageFooter/>
        </div>
      </body>
    </html>
  )
}
